title: Canada Sales Manufacturing
logo: /assets/img/Canada_manufacturing.png
description:  This project is for learning and experimentation purposes only
show_downloads:  True
theme: jekyll-theme-minimal