-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dim_naics
(
    id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT dim_naics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dim_province
(
    id integer NOT NULL,
    name character varying(50) COLLATE pg_catalog."default",
    latitude character varying(20) COLLATE pg_catalog."default",
    longitude character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT dim_province_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dim_seasonal_adjustment
(
    id integer NOT NULL,
    name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT dim_seasonal_adjustment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.fact_sales
(
    date_sales date,
    id_province integer,
    id_seasonal integer,
    id_naics character varying(10) COLLATE pg_catalog."default",
    value double precision
);

ALTER TABLE IF EXISTS public.fact_sales
    ADD CONSTRAINT fact_sales_id_naics_fkey FOREIGN KEY (id_naics)
    REFERENCES public.dim_naics (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_sales
    ADD CONSTRAINT fact_sales_id_province_fkey FOREIGN KEY (id_province)
    REFERENCES public.dim_province (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_sales
    ADD CONSTRAINT fact_sales_id_seasonal_fkey FOREIGN KEY (id_seasonal)
    REFERENCES public.dim_seasonal_adjustment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;